version: "3"
services:
  aplweb:
    container_name: aplweb
    image: aplsystems/web-rails
    networks:
      - apl
    ports:
      - "8080:80"
    volumes:
      - "/vol/aplweb:/usr/src"
      - "gitlabssh:/root/.ssh"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=aplweb,aplweb.localhost
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - apl
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=aplweb_production
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
  adminer:
    container_name: adminer
    image: adminer
    networks:
      - apl
    ports:
      - "8087:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
  proxy:
    container_name: proxy
    image: nginxproxy/nginx-proxy
    networks:
      - apl
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: unless-stopped
    environment:
      - DEFAULT_HOST=aplweb

volumes:
  mariadb: {}
  gitlabssh: {}

networks:
  apl:
    name: apl
    attachable: true
